### ISSUE TITLE
Add option "allow collapse all" and "active section"

### ISSUE THREAD

**Issue by phucbm** [viivue/easy-tab-accordion#3]
Add new options:

## 2. Active section `active_section`

- `active_section:0` => default
- `active_section:1` => open the 2nd section
- `active_section:-1` => open nothing

**Comment by phucbm** [comment]
We need these options back in the HTML of VC Accordion @daomapsieucap

**Comment by daomapsieucap** [comment]
@zrvincent @tung13041996 : Done with commit https://github.com/viivue/bcnb/commit/36ecb66fcfdfdb84669863c48b6f0d5f387fb64a

**Comment by phucbm** [comment]
Added in version [v1.0.1](https://github.com/viivue/easy-tab-accordion/releases/tag/v1.0.1)

**Comment by phucbm** [comment]
Good job @tung13041996  🎉
