### ISSUE TITLE
Easy Tab Accordion has a white flash effect when navigating between each tab

### ISSUE THREAD

**Issue by vuquangpham** [viivue/easy-tab-accordion#38]
## Problem
This problem has occurred because of the transition property of the inline style.

![ezgif-2-fef76b9632](https://user-images.githubusercontent.com/30406982/231444210-49bc0bc9-e78f-4fad-9213-c5d554ca1603.gif)

## Solution
- Use `transition` property directly on the `receiver` element in the CSS file

![ezgif-2-632e98c878](https://user-images.githubusercontent.com/30406982/231444580-5c763a6d-d005-4f46-a6ee-0109a493fcf6.gif)

**Comment by phucbm** [comment]
Closed due to being inactive for a long time.
