### ISSUE TITLE
Calculate wrong height 

### ISSUE THREAD

**Issue by vuquangpham** [viivue/easy-tab-accordion#41]
## Problem
- ETA has calculated the wrong height between the parent element and the child element

Parent element:
![parent-crop](https://github.com/viivue/easy-tab-accordion/assets/30406982/2cd42b47-386d-4d97-9607-2ee233deb1c2)

Child element:
![crop-image](https://github.com/viivue/easy-tab-accordion/assets/30406982/d37269d5-50b1-4730-97eb-3766aa78b827)

Because of that, we can't see the border-bottom from the child element.

**Comment by phucbm** [comment]
Closed due to no new report on this issue.
